version: '3.9'

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  psql:
    container_name: psql
    image: timescale/timescaledb:latest-pg12
    environment:
      # https://www.postgresql.org/docs/current/libpq-envars.html
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
    command: ["sh", "-c", "sleep 5 && psql -h timescaledb -p 5432 -f /tmp/init_table.sql"]
    depends_on: 
      - timescaledb
    volumes:
      - ./init_table.sql:/tmp/init_table.sql
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes: 
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  publisher:
    container_name: publisher
    build:
      context: ../
      args:
        TEMPLATE: mqtt2timescale/publisher
        INIT_DELAY: 10
    volumes: 
      - ./publisher/catalogs:/opt/app/catalogs
      - ./data:/opt/app/data
    depends_on: 
      - timescaledb
      - psql
      - mosquitto
      - subscriber
    ports:
      - "8000:8000"
  subscriber:
    container_name: subscriber
    build:
      context: ../
      args:
        TEMPLATE: mqtt2timescale/subscriber
        INIT_DELAY: 7
    volumes: 
      - ./subscriber/catalogs:/opt/app/catalogs
      - ./data:/opt/app/data
    depends_on: 
      - timescaledb
      - psql
      - mosquitto
    ports:
      - "8100:8100"
